# Site settings
baseurl = "/"
languageCode = "en-us"
title = "BEL.bio"
theme = "syna"
googleAnalytics = "UA-151906497-1"
enableGitInfo = true
version = "0.15.0"

[markup]
   defaultMarkdownHandler = "blackfriday"

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

# Google Analytics tracking
googleAnalytics = ""

[params]
  name = "BEL.bio"
  description = "BEL website"

  [params.style]
    background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    # favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    # favicon_svg = "favicon.svg"

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#00838F"
    secondary = "#dddddd"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#343a40"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = "/"
  name = "Home"
  weight = 10


[[menu.main]]
  url = "/resources"
  name = "Resources"
  weight = 15

[[menu.main]]
  url = "/about"
  name = "About Us"
  weight = 30

[[menu.main]]
  url = "/faq"
  name = "FAQ"
  weight = 20

# [[menu.footer]]
#   url = "#"
#   name = "Link"
#   weight = 10#

# [[menu.footer]]
#   url = "#"
#   name = "Long Link"
#   weight = 30#

# [[menu.footer]]
#   url = "#"
#   name = "Tiny Link"
#   weight = 30

[[menu.copyright_footer]]
  url = "https://forum.bel.bio"
  name = "BEL Discussion Forum"
  weight = 10

[[menu.copyright_footer]]
  url = "https://language.bel.bio"
  name = "BEL Language Docs"
  weight = 30


